latest code

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -1,21 +1,54 @@
-name: Build
+name: SonarCloud Quality Gate
 on:
-  push:
-    branches:
-      - main
   pull_request:
-    types: [opened, synchronize, reopened]
+    types:
+      - opened
+      - synchronize
 jobs:
-
   sonarcloud:
-    name: SonarCloud
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: SonarCloud Scan
+          node-version: 14
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Build React app
+        run: npm run build
+
+      - name: Run SonarCloud analysis
         uses: SonarSource/sonarcloud-github-action@master
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          organization: ghulamhaider12
+          projectKey: Ghulamhaider12_maqware-website
+          projectName: 'maqware-website'
+          scannerEnabled: true
+          scannerVersion: latest
+          extraProperties: |
+            sonar.sources=src
+            sonar.exclusions=**/*.test.js,**/node_modules/**
+            sonar.tests=src
+            sonar.test.inclusions=**/*.test.js
+            sonar.javascript.lcov.reportPaths=coverage/lcov.info
+            sonar.javascript.lcov.reportPaths=coverage/lcov-report/*.lcov
+            sonar.coverage.exclusions=**/*.test.js
+      - name: Check SonarCloud Quality Gate
+        id: check_sonarcloud
+        run: |
+          quality_gate_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: -X GET "https://sonarcloud.io/api/project_badges/measure?project=Ghulamhaider12_maqware-website&metric=alert_status" | jq -r '.projectStatus.status')
+          echo "SonarCloud Quality Gate Status: $quality_gate_status"
+          echo "::set-output name=quality_gate_status::$quality_gate_status"
+
+      - name: Prevent PR Merge
+        if: steps.check_sonarcloud.outputs.quality_gate_status != 'PASSED'
+        run: |
+          echo "SonarCloud quality gate failed. Please fix the code quality issues before merging the pull request."
+          exit 1
